\" Manpage for www.
.\" To correct errors or typos please use https://github.com/nbari/www/issues
.TH man 1 "October 2018" "www" "www man page"
.SH NAME
www \- static web server
.SH SYNOPSIS
www [options] command arguments ...
.SH DESCRIPTION

.SH BUGS
https://github.com/nbari/www/issues
.SH AUTHOR
.PP
Nicolas Embriz <nbari@tequila.io>
.br
For more information, see the www homepage at
.br
https://go-www.com
